@startuml Consultorio
package Clinica
{
   
    
    package Inventario
    {

        interface Insumo {
            Cantidad:int
            AddCantidad(int):void
            VerCantidad():int
            RestarCantidad(int):void
        }
        class Medicamento {}
        class Desechables {}
    }
    package Personas
    {

    enum TurnoTrabajo{
        DIA
        TARDE
        NOCHE
    }
    enum Sexo{
        MASCULINO
        FEMENINO
        OTRO
    }
    enum Prevision{
        FONASA
        ISAPRE
    }

    enum AFP{
        CAPITAL
        HABITAT
        UNO
        CUPRUM
        MODELO
        PLANVITAL
        PROVIDA
    }
        class Persona
        {
        - rut: int
        - digitoVerificador: int
        - sexo: Sexo
        - fechaNacimiento:DateTime
        - edad:int
        - direccion: string
        - telefono: int
        - Prevision: prevision
        }

        package TrabajadoresExt
        {
        interface ITrabajadoresExternos{
            EmpresaContratista: string
        }
         class Limpieza{}

        class Seguridad{
        }
        }
        package Clientes
        {
            interface ICliente{
            MotivaDeConsulta:string
            fechaAtencion: DateTime
        }

        enum Relacion{
            PADRE
            MADRE
            HIJO
            HIJA
            OTRO
        }
         class Paciente{
            - motivoDeConsulta: string
            - tieneTutor: bool
            - fechaAtencion: DateTime
        }
        class Tutor{
            - relacionPaciente: Relacion
        }
        }
        

        
        package Usuarios
        {
            interface IUsuario
            {
                LogIn(string,string):void
                LogOut():void
                UserName:string
                Password:string
            }
            class Secretario{
                -userName: string
                -password: string
            }

            class Medico{
                - userName:string
            }

            class Gerente
            {
                -nombre: string
                -contrasenhia: string

            }
          
        }
        package Infraestructura
         {
             interface IInfraestructura{
                 CapacidadPersonasMax: int
                 ContadorPersonasActuales:int
                 AddPersonaActual(int):void
                 EliminarPersonaActual(int):void
             }
             class Box{
                 medicoDeTurno: Medico
                 CambioDeTurno(Medico):void
                 LimpiarBox(List<Limipieza>):void
             }
             class SalaDeEspera {
                 seguridadDeTurno: List<Seguridad>
                 CambioDeTurno(List<Seguridad>): void
             }
             

         }
        'Relaciones
        'Herencias
        Persona<|-- Tutor
       
        'Composicion
        '(Se tienen en campo y no existen sin estar dentro de la clase)
        Paciente *-- Tutor
        'Agregacion
        '(Se tienen en campo pero existen independiente)
        Box o-- Medico
        SalaDeEspera o-- Seguridad
        Box o-- Medicamento
        Box o-- Desechables
        'Asociacion
        '(Interactuan pero son independientes, ej: pueden estar en metodo de el objeto)
        Box "2" -- Limpieza

        'Interfaces:

        'Herencias Interfaces
        Persona <|-- ITrabajadoresExternos
        Persona <|-- ICliente
        Persona <|-- IUsuario
        'Interfaz T externos
        ITrabajadoresExternos <|.. Limpieza
        ITrabajadoresExternos <|.. Seguridad
        'Interfaz Usuarios
        IUsuario <|.. Secretario
        IUsuario <|.. Gerente
        IUsuario <|.. Medico
        'Interfaz Clientes
        ICliente <|.. Paciente
        'Interfaz Insumos
        Insumo <|.. Medicamento
        Insumo <|.. Desechables
        'Interfaz Infraestructura
        IInfraestructura <|.. Box
        IInfraestructura <|.. SalaDeEspera
        
    }
    
}
@enduml