@startuml clinicaApp
class Persona{
    - rut: int
    - digitoVerificador: int
    - sexo: Sexo
    - fechaNacimiento:DateTime
    - edad:int
    - direccion: string
    - telefono: int 
    - Prevision: prevision
}
class Paciente{
    - motivoDeConsulta: string 
    - tieneTutor: bool
    - fechaAtencion: DateTime
}
class Tutor{
    - relacionPaciente: Relacion
}
class Secretarios{}
class Limpieza{}
class Medico{

}
class Gerencia{}
class Medicamento {}
class Desechables {}
class SalaDeEspera {}
class Box{}
class TENS{}
class Seguridad{}

interface Trabajadores{}
interface Insumo {}
interface Infraestructura{}
interface Cliente{}

enum Sexo{
    MASCULINO
    FEMENINO
}
enum Prevision{
    FONASA
    ISAPRE
}

enum AFP{
    CAPITAL
    HABITAT
    UNO
    CUPRUM
    MODELO
    PLANVITAL
    PROVIDA
}
enum Relacion{
    PADRE
    MADRE
    HIJO
    HIJA
    OTRO
}
enum TurnoTrabajo{
    DIA
    TARDE
    NOCHE
}

'Relaciones 
'Herencias
Persona<-- Paciente 
Persona<-- Secretarios 
Persona<-- Limpieza 
Persona<-- Medico 
Persona<-- Gerencia 
Persona<-- Seguridad 
'Asociaciones
Paciente -- Tutor
@enduml

